FROM python:3.10.11-slim-buster

# Install required packages
RUN apt-get update && \
    apt-get install -y python3 python3-pip

# Create and set the working directory
WORKDIR /app

# Copy the env folder and app.py into the container
COPY app.py /app/app.py

RUN pip3 install --upgrade pip

# Install Python dependencies
RUN pip3 install -q super-gradients==3.1.1 roboflow supervision

# Set the entry point
ENTRYPOINT ["python3", "app.py"]